FROM eclipse-temurin: 17-jdk
ENV DEBIAN_ENVIORNMENT=noninteractive
RUN apt update -y && apt install maven -y && apt install mysql-server -y
WORKDIR /app
COPY app/pom.xml .
COPY app/src ./src
COPY init.sql /init.sql
COPY start.sh /start.sh
RUN chmod +x /start.sh
EXPOSE 8080
CMD ["/start.sh"]
